
spring:
  application:
    name: cloud-feign
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8777

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8660/eureka/ # 注册地址
feign:
  hystrix:
    enabled: true  # 开启熔断器
